[tool.poetry]
name = "neori"
version = "0.1.0"
description = ""
authors = ["Jorge Brito <jorge.brito.json@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
